11. Better Simulations and HMM estimations
-------------------------------------
```{r eval=TRUE, echo=FALSE}

source("SharedFunctions.R")

```

#### Simulating and estimating for 10,000 loci
recombination rate = 0.0002 
```{r}
#set.seed(1234455)
start.p<-c(0.25,0.25,0.25,0.25)
recombination.rate<-0.0002
prob.missing=0.1
trans.p<-GetTransitionProb(recombination.rate)
child1.chromatid.mom<-SimulateChromatid(10000,recombination.rate) 
child1.chromatid.dad<-SimulateChromatid(10000,recombination.rate)
old_obs<-child1.chromatid.mom$child+child1.chromatid.dad$child
obs<-GetDiploidGenotypeWithErrors(child1.chromatid.mom,child1.chromatid.dad,0.1)
old_obs[1:10]
obs[1:10]
v.2<-ViterbiWithMissingDataAndError (obs,start.p, trans.p,child1.chromatid.mom,child1.chromatid.dad,prob.missing)
 
vitrowmax.2 <- apply(v.2, 1, function(x) which.max(x))
#vitrowmax.2
simulated<-paste("mom.",child1.chromatid.mom$parent.path,"/","dad.",child1.chromatid.dad$parent.path,sep="")
estimated<-rownames(trans.p)[vitrowmax.2]
sim.results<-sum(simulated==estimated)

```
The number for true positives from our estimation would be given by. 
```{r}
sum(sim.results)
CountRecombEvents(estimated)
CountRecombEvents(simulated)
simulated[1:10]
estimated[1:10]

```
and the percentage of true positives is `r  sum(sim.results)/10000*100`%



#### Author
Luis Avila (lmavila@gmail.com)